# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.10.0.schema.json

PackageIdentifier: AtestaAnalytics.FlightPathServer
PackageVersion: 0.0.1-alpha
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.10.0
